(define-module (pip-tui pip-color-names))
(define-public COLOR_INDEX_BLACK 16)
(define-public COLOR_INDEX_BLUE4 18)
(define-public COLOR_INDEX_DARKBLUE 18)
(define-public COLOR_INDEX_MEDIUMBLUE 20)
(define-public COLOR_INDEX_BLUE3 20)
(define-public COLOR_INDEX_BLUE 21)
(define-public COLOR_INDEX_BLUE1 21)
(define-public COLOR_INDEX_PIPGREEN5 22)
(define-public COLOR_INDEX_DEEPSKYBLUE4 24)
(define-public COLOR_INDEX_ROYALBLUE 26)
(define-public COLOR_INDEX_PIPGREEN4 28)
(define-public COLOR_INDEX_CYAN4 30)
(define-public COLOR_INDEX_DARKCYAN 30)
(define-public COLOR_INDEX_PIPGREEN3 34)
(define-public COLOR_INDEX_LIGHTSEAGREEN 37)
(define-public COLOR_INDEX_PIPGREEN2 40)
(define-public COLOR_INDEX_CYAN3 44)
(define-public COLOR_INDEX_GREEN 46)
(define-public COLOR_INDEX_LIME 46)
(define-public COLOR_INDEX_X11GREEN 46)
(define-public COLOR_INDEX_GREEN1 46)
(define-public COLOR_INDEX_PIPGREEN1 46)
(define-public COLOR_INDEX_SPRINGGREEN 48)
(define-public COLOR_INDEX_SPRINGGREEN1 48)
(define-public COLOR_INDEX_CYAN 51)
(define-public COLOR_INDEX_AQUA 51)
(define-public COLOR_INDEX_CYAN1 51)
(define-public COLOR_INDEX_PIPINDIGO 54)
(define-public COLOR_INDEX_GRAY37 59)
(define-public COLOR_INDEX_GREY37 59)
(define-public COLOR_INDEX_SLATEBLUE3 62)
(define-public COLOR_INDEX_DARKSEAGREEN4 65)
(define-public COLOR_INDEX_PALETURQUOISE4 66)
(define-public COLOR_INDEX_CORNFLOWERBLUE 68)
(define-public COLOR_INDEX_SKYBLUE3 74)
(define-public COLOR_INDEX_STEELBLUE1 75)
(define-public COLOR_INDEX_CHARTREUSE3 76)
(define-public COLOR_INDEX_SEAGREEN3 78)
(define-public COLOR_INDEX_MEDIUMAQUAMARINE 79)
(define-public COLOR_INDEX_AQUAMARINE3 79)
(define-public COLOR_INDEX_MEDIUMTURQUOISE 80)
(define-public COLOR_INDEX_PIPLIGHTGREEN4 83)
(define-public COLOR_INDEX_AQUAMARINE 86)
(define-public COLOR_INDEX_AQUAMARINE1 86)
(define-public COLOR_INDEX_RED4 88)
(define-public COLOR_INDEX_DARKRED 88)
(define-public COLOR_INDEX_MAROON4 89)
(define-public COLOR_INDEX_MAGENTA4 90)
(define-public COLOR_INDEX_DARK_MAGENTA 90)
(define-public COLOR_INDEX_DARKMAGENTA 90)
(define-public COLOR_INDEX_DARKVIOLET 92)
(define-public COLOR_INDEX_DARKGOLDENROD4 94)
(define-public COLOR_INDEX_LIGHTPINK4 95)
(define-public COLOR_INDEX_PLUM4 96)
(define-public COLOR_INDEX_YELLOW4 100)
(define-public COLOR_INDEX_GRAY53 102)
(define-public COLOR_INDEX_GREY53 102)
(define-public COLOR_INDEX_DARKSEAGREEN 108)
(define-public COLOR_INDEX_SKYBLUE3 110)
(define-public COLOR_INDEX_PALEGREEN3 114)
(define-public COLOR_INDEX_DARKSLATEGRAY3 116)
(define-public COLOR_INDEX_LIGHTSKYBLUE 117)
(define-public COLOR_INDEX_CHARTREUSE 118)
(define-public COLOR_INDEX_CHARTREUSE1 118)
(define-public COLOR_INDEX_PIPLIGHTGREEN3 120)
(define-public COLOR_INDEX_AQUAMARINE 122)
(define-public COLOR_INDEX_AQUAMARINE1 122)
(define-public COLOR_INDEX_DARKSLATEGRAY1 123)
(define-public COLOR_INDEX_MEDIUMORCHID3 134)
(define-public COLOR_INDEX_DARKGOLDENROD 136)
(define-public COLOR_INDEX_ROSYBROWN 138)
(define-public COLOR_INDEX_MEDIUMPURPLE1 141)
(define-public COLOR_INDEX_DARKKHAKI 143)
(define-public COLOR_INDEX_GRAY69 145)
(define-public COLOR_INDEX_GREY69 145)
(define-public COLOR_INDEX_DARKOLIVEGREEN3 149)
(define-public COLOR_INDEX_POWDERBLUE 152)
(define-public COLOR_INDEX_GREENYELLOW 154)
(define-public COLOR_INDEX_PIPLIGHTGREEN2 157)
(define-public COLOR_INDEX_PALETURQUOISE1 159)
(define-public COLOR_INDEX_RED3 160)
(define-public COLOR_INDEX_VIOLETRED 162)
(define-public COLOR_INDEX_MAGENTA3 164)
(define-public COLOR_INDEX_INDIANRED 167)
(define-public COLOR_INDEX_MEDIUMORCHID1 171)
(define-public COLOR_INDEX_ORANGE3 172)
(define-public COLOR_INDEX_LIGHTSALMON3 173)
(define-public COLOR_INDEX_GOLD3 178)
(define-public COLOR_INDEX_BURLYWOOD3 180)
(define-public COLOR_INDEX_YELLOW3 184)
(define-public COLOR_INDEX_KHAKI3 186)
(define-public COLOR_INDEX_LEMONCHIFFON3 187)
(define-public COLOR_INDEX_GRAY84 188)
(define-public COLOR_INDEX_GREY84 188)
(define-public COLOR_INDEX_PIPLIGHTGREEN1 194)
(define-public COLOR_INDEX_LIGHTCYAN 195)
(define-public COLOR_INDEX_LIGHTCYAN1 195)
(define-public COLOR_INDEX_RED 196)
(define-public COLOR_INDEX_RED1 196)
(define-public COLOR_INDEX_DEEPPINK 198)
(define-public COLOR_INDEX_DEEPPINK1 198)
(define-public COLOR_INDEX_MAGENTA 201)
(define-public COLOR_INDEX_FUCHSIA 201)
(define-public COLOR_INDEX_MAGENTA1 201)
(define-public COLOR_INDEX_INDIANRED1 203)
(define-public COLOR_INDEX_HOTPINK 205)
(define-public COLOR_INDEX_DARKORANGE 208)
(define-public COLOR_INDEX_SALMON1 209)
(define-public COLOR_INDEX_LIGHTCORAL 210)
(define-public COLOR_INDEX_PALEVIOLETRED1 211)
(define-public COLOR_INDEX_ORCHID1 213)
(define-public COLOR_INDEX_DARKGOLDENROD1 214)
(define-public COLOR_INDEX_SANDYBROWN 215)
(define-public COLOR_INDEX_LIGHTPINK1 217)
(define-public COLOR_INDEX_GOLD 220)
(define-public COLOR_INDEX_GOLD1 220)
(define-public COLOR_INDEX_PEACHPUFF 223)
(define-public COLOR_INDEX_PEACHPUFF1 223)
(define-public COLOR_INDEX_MISTYROSE 224)
(define-public COLOR_INDEX_MISTYROSE1 224)
(define-public COLOR_INDEX_MISTYROSE2 224)
(define-public COLOR_INDEX_THISTLE1 225)
(define-public COLOR_INDEX_YELLOW 226)
(define-public COLOR_INDEX_YELLOW1 226)
(define-public COLOR_INDEX_LIGHTGOLDENRODYELLOW 230)
(define-public COLOR_INDEX_WHITE 231)
(define-public COLOR_INDEX_GRAY3 232)
(define-public COLOR_INDEX_GREY3 232)
(define-public COLOR_INDEX_GRAY7 233)
(define-public COLOR_INDEX_GREY7 233)
(define-public COLOR_INDEX_GRAY11 234)
(define-public COLOR_INDEX_GREY11 234)
(define-public COLOR_INDEX_GRAY15 235)
(define-public COLOR_INDEX_GREY15 235)
(define-public COLOR_INDEX_GRAY19 236)
(define-public COLOR_INDEX_GREY19 236)
(define-public COLOR_INDEX_GRAY23 237)
(define-public COLOR_INDEX_GREY23 237)
(define-public COLOR_INDEX_GRAY27 238)
(define-public COLOR_INDEX_GREY27 238)
(define-public COLOR_INDEX_GRAY30 239)
(define-public COLOR_INDEX_GREY30 239)
(define-public COLOR_INDEX_GRAY31 239)
(define-public COLOR_INDEX_GREY31 239)
(define-public COLOR_INDEX_GRAY34 240)
(define-public COLOR_INDEX_GREY34 240)
(define-public COLOR_INDEX_GRAY35 240)
(define-public COLOR_INDEX_GREY35 240)
(define-public COLOR_INDEX_GRAY38 241)
(define-public COLOR_INDEX_GREY38 241)
(define-public COLOR_INDEX_GRAY39 241)
(define-public COLOR_INDEX_GREY39 241)
(define-public COLOR_INDEX_GRAY42 242)
(define-public COLOR_INDEX_GREY42 242)
(define-public COLOR_INDEX_GRAY46 243)
(define-public COLOR_INDEX_GREY46 243)
(define-public COLOR_INDEX_WEBGRAY 244)
(define-public COLOR_INDEX_WEBGREY 244)
(define-public COLOR_INDEX_GRAY54 245)
(define-public COLOR_INDEX_GREY54 245)
(define-public COLOR_INDEX_GRAY58 246)
(define-public COLOR_INDEX_GREY58 246)
(define-public COLOR_INDEX_GRAY62 247)
(define-public COLOR_INDEX_GREY62 247)
(define-public COLOR_INDEX_GRAY66 248)
(define-public COLOR_INDEX_GREY66 248)
(define-public COLOR_INDEX_GRAY70 249)
(define-public COLOR_INDEX_GREY70 249)
(define-public COLOR_INDEX_GRAY74 250)
(define-public COLOR_INDEX_GREY74 250)
(define-public COLOR_INDEX_GRAY78 251)
(define-public COLOR_INDEX_GREY78 251)
(define-public COLOR_INDEX_GRAY81 252)
(define-public COLOR_INDEX_GREY81 252)
(define-public COLOR_INDEX_GRAY82 252)
(define-public COLOR_INDEX_GREY82 252)
(define-public COLOR_INDEX_GRAY85 253)
(define-public COLOR_INDEX_GREY85 253)
(define-public COLOR_INDEX_GRAY86 253)
(define-public COLOR_INDEX_GREY86 253)
(define-public COLOR_INDEX_GRAY89 254)
(define-public COLOR_INDEX_GREY89 254)
(define-public COLOR_INDEX_GRAY90 254)
(define-public COLOR_INDEX_GREY90 254)
(define-public COLOR_INDEX_GRAY93 255)
(define-public COLOR_INDEX_GREY93 255)

(define-public COLOR_NAMES_COUNT 118)

(define-public COLOR_NAMES '
  (()
   ()
   ()
   ()
   ()
   ()
   ()
   ()
   ()
   ()
   ()
   ()
   ()
   ()
   ()
   ()
   ("BLACK")
   ()
   ("BLUE4" "DARKBLUE")
   ()
   ("MEDIUMBLUE" "BLUE3")
   ("BLUE" "BLUE1")
   ("PIPGREEN5")
   ()
   ("DEEPSKYBLUE4")
   ()
   ("ROYALBLUE")
   ()
   ("PIPGREEN4")
   ()
   ("CYAN4" "DARKCYAN")
   ()
   ()
   ()
   ("PIPGREEN3")
   ()
   ()
   ("LIGHTSEAGREEN")
   ()
   ()
   ("PIPGREEN2")
   ()
   ()
   ()
   ("CYAN3")
   ()
   ("GREEN" "LIME" "X11GREEN" "GREEN1" "PIPGREEN1")
   ()
   ("SPRINGGREEN" "SPRINGGREEN1")
   ()
   ()
   ("CYAN" "AQUA" "CYAN1")
   ()
   ()
   ("PIPINDIGO")
   ()
   ()
   ()
   ()
   ("GRAY37" "GREY37")
   ()
   ()
   ("SLATEBLUE3")
   ()
   ()
   ("DARKSEAGREEN4")
   ("PALETURQUOISE4")
   ()
   ("CORNFLOWERBLUE")
   ()
   ()
   ()
   ()
   ()
   ("SKYBLUE3")
   ("STEELBLUE1")
   ("CHARTREUSE3")
   ()
   ("SEAGREEN3")
   ("MEDIUMAQUAMARINE" "AQUAMARINE3")
   ("MEDIUMTURQUOISE")
   ()
   ()
   ("PIPLIGHTGREEN4")
   ()
   ()
   ("AQUAMARINE" "AQUAMARINE1")
   ()
   ("RED4" "DARKRED")
   ("MAROON4")
   ("MAGENTA4" "DARK MAGENTA" "DARKMAGENTA")
   ()
   ("DARKVIOLET")
   ()
   ("DARKGOLDENROD4")
   ("LIGHTPINK4")
   ("PLUM4")
   ()
   ()
   ()
   ("YELLOW4")
   ()
   ("GRAY53" "GREY53")
   ()
   ()
   ()
   ()
   ()
   ("DARKSEAGREEN")
   ()
   ("SKYBLUE3")
   ()
   ()
   ()
   ("PALEGREEN3")
   ()
   ("DARKSLATEGRAY3")
   ("LIGHTSKYBLUE")
   ("CHARTREUSE" "CHARTREUSE1")
   ()
   ("PIPLIGHTGREEN3")
   ()
   ("AQUAMARINE" "AQUAMARINE1")
   ("DARKSLATEGRAY1")
   ()
   ()
   ()
   ()
   ()
   ()
   ()
   ()
   ()
   ()
   ("MEDIUMORCHID3")
   ()
   ("DARKGOLDENROD")
   ()
   ("ROSYBROWN")
   ()
   ()
   ("MEDIUMPURPLE1")
   ()
   ("DARKKHAKI")
   ()
   ("GRAY69" "GREY69")
   ()
   ()
   ()
   ("DARKOLIVEGREEN3")
   ()
   ()
   ("POWDERBLUE")
   ()
   ("GREENYELLOW")
   ()
   ()
   ("PIPLIGHTGREEN2")
   ()
   ("PALETURQUOISE1")
   ("RED3")
   ()
   ("VIOLETRED")
   ()
   ("MAGENTA3")
   ()
   ()
   ("INDIANRED")
   ()
   ()
   ()
   ("MEDIUMORCHID1")
   ("ORANGE3")
   ("LIGHTSALMON3")
   ()
   ()
   ()
   ()
   ("GOLD3")
   ()
   ("BURLYWOOD3")
   ()
   ()
   ()
   ("YELLOW3")
   ()
   ("KHAKI3")
   ("LEMONCHIFFON3")
   ("GRAY84" "GREY84")
   ()
   ()
   ()
   ()
   ()
   ("PIPLIGHTGREEN1")
   ("LIGHTCYAN" "LIGHTCYAN1")
   ("RED" "RED1")
   ()
   ("DEEPPINK" "DEEPPINK1")
   ()
   ()
   ("MAGENTA" "FUCHSIA" "MAGENTA1")
   ()
   ("INDIANRED1")
   ()
   ("HOTPINK")
   ()
   ()
   ("DARKORANGE")
   ("SALMON1")
   ("LIGHTCORAL")
   ("PALEVIOLETRED1")
   ()
   ("ORCHID1")
   ("DARKGOLDENROD1")
   ("SANDYBROWN")
   ()
   ("LIGHTPINK1")
   ()
   ()
   ("GOLD" "GOLD1")
   ()
   ()
   ("PEACHPUFF" "PEACHPUFF1")
   ("MISTYROSE" "MISTYROSE1" "MISTYROSE2")
   ("THISTLE1")
   ("YELLOW" "YELLOW1")
   ()
   ()
   ()
   ("LIGHTGOLDENRODYELLOW")
   ("WHITE")
   ("GRAY3" "GREY3")
   ("GRAY7" "GREY7")
   ("GRAY11" "GREY11")
   ("GRAY15" "GREY15")
   ("GRAY19" "GREY19")
   ("GRAY23" "GREY23")
   ("GRAY27" "GREY27")
   ("GRAY30" "GREY30" "GRAY31" "GREY31")
   ("GRAY34" "GREY34" "GRAY35" "GREY35")
   ("GRAY38" "GREY38" "GRAY39" "GREY39")
   ("GRAY42" "GREY42")
   ("GRAY46" "GREY46")
   ("WEBGRAY" "WEBGREY")
   ("GRAY54" "GREY54")
   ("GRAY58" "GREY58")
   ("GRAY62" "GREY62")
   ("GRAY66" "GREY66")
   ("GRAY70" "GREY70")
   ("GRAY74" "GREY74")
   ("GRAY78" "GREY78")
   ("GRAY81" "GREY81" "GRAY82" "GREY82")
   ("GRAY85" "GREY85" "GRAY86" "GREY86")
   ("GRAY89" "GREY89" "GRAY90" "GREY90")
   ("GRAY93" "GREY93"))
  )
